rotate(a=180,v=[1000,0,0]){
  rotate(a=-90,v=[0,1000,0]){
    translate([13,0,0]){
      rotate(a=90,v=[0,0,1000]){
        translate([0,3,0]){
          difference(){
            difference(){
              difference(){
                translate([0,-5,0]){
                  rotate(a=90,v=[0,0,1000]){
                    translate([-5,0,0]){
                      rotate(a=90,v=[0,0,1000]){
                        translate([0,-5,0]){
                          rotate(a=90,v=[0,0,1000]){
                            rotate([0,-90,0]){cylinder($fn=100,h=10,r=7,center=true);}
                          }
                        }
                        translate([0,-0.4,0]){
                          translate([0,-0.5,0]){
                            cube([14.6,1,1],center=true);
                          }
                          translate([0,-2.05,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                          }
                          translate([0,-4.1,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                          }
                          translate([0,-6.15,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                          }
                          translate([0,-8.2,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                          }
                          rotate(a=18,v=[0,1000,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                            translate([0,-2.05,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-4.1,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-6.15,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-8.2,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                          }
                          rotate(a=36,v=[0,1000,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                            translate([0,-2.05,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-4.1,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-6.15,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-8.2,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                          }
                          rotate(a=54,v=[0,1000,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                            translate([0,-2.05,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-4.1,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-6.15,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-8.2,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                          }
                          rotate(a=72,v=[0,1000,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                            translate([0,-2.05,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-4.1,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-6.15,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-8.2,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                          }
                          rotate(a=90,v=[0,1000,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                            translate([0,-2.05,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-4.1,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-6.15,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-8.2,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                          }
                          rotate(a=108,v=[0,1000,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                            translate([0,-2.05,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-4.1,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-6.15,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-8.2,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                          }
                          rotate(a=126,v=[0,1000,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                            translate([0,-2.05,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-4.1,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-6.15,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-8.2,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                          }
                          rotate(a=144,v=[0,1000,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                            translate([0,-2.05,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-4.1,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-6.15,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-8.2,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                          }
                          rotate(a=162,v=[0,1000,0]){
                            translate([0,-0.5,0]){
                              cube([14.6,1,1],center=true);
                            }
                            translate([0,-2.05,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-4.1,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-6.15,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                            translate([0,-8.2,0]){
                              translate([0,-0.5,0]){
                                cube([14.6,1,1],center=true);
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
                rotate(a=90,v=[0,0,1000]){
                  rotate([0,-90,0]){cylinder($fn=100,h=100,r=1.5,center=true);}
                }
              }
              rotate(a=90,v=[0,0,1000]){
                rotate([0,-90,0]){cylinder($fn=100,h=6,r=4.5,center=true);}
              }
            }
            translate([0,-6,0]){
              rotate(a=-90,v=[1000,0,0]){
                translate([0,0,-10]){
                  rotate(a=-90,v=[0,1000,0]){
                    rotate([0,-90,0]){cylinder($fn=6,h=20,r=3.34863,center=true);}
                  }
                }
                translate([0,0,0.35]){
                  intersection(){
                    translate([0,0,-10]){
                      rotate(a=-90,v=[0,1000,0]){
                        rotate([0,-90,0]){cylinder($fn=6,h=20,r=3.34863,center=true);}
                      }
                    }
                    cube([3,100,100],center=true);
                  }
                }
                translate([0,0,0.7]){
                  intersection(){
                    translate([0,0,-10]){
                      rotate(a=-90,v=[0,1000,0]){
                        rotate([0,-90,0]){cylinder($fn=6,h=20,r=3.34863,center=true);}
                      }
                    }
                    cube([3,3,100],center=true);
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
