translate([0,0,21]) {
group(){
  difference(){
    difference(){
      difference(){
        difference(){
          difference(){
            difference(){
              difference(){
                difference(){
                  difference(){
                    group(){
                      difference(){
                        group(){
                          difference(){
                            difference(){
                              difference(){
                                group(){
                                  difference(){
                                    difference(){
                                      difference(){
                                        group(){
                                          difference(){
                                            difference(){
                                              group(){
                                                difference(){
                                                  group(){
                                                    difference(){
                                                      group(){
                                                        translate([12.5,0,-7]){
                                                          translate([-1.65,0,0]){
                                                            cube([0.7,35,1.2],center=true);
                                                          }
                                                          translate([-4,0,0]){
                                                            translate([0,19.85,0]){
                                                              translate([-6.25,0,0]){
                                                                cube([12.5,0.7,1.2],center=true);
                                                              }
                                                            }
                                                            translate([0,-19.85,0]){
                                                              translate([-6.25,0,0]){
                                                                cube([12.5,0.7,1.2],center=true);
                                                              }
                                                            }
                                                          }
                                                        }
                                                        translate([12.5,0,-7]){
                                                          translate([-1,0,-8]){
                                                            cube([2,43,16],center=true);
                                                          }
                                                          translate([-60,0,0]){
                                                            translate([1,0,-8]){
                                                              cube([2,43,16],center=true);
                                                            }
                                                          }
                                                          translate([0,21.5,0]){
                                                            translate([-30,-1,-8]){
                                                              cube([60,2,16],center=true);
                                                            }
                                                          }
                                                          translate([0,-21.5,0]){
                                                            translate([-30,1,-8]){
                                                              cube([60,2,16],center=true);
                                                            }
                                                          }
                                                          translate([0,0,-16]){
                                                            translate([-30,0,1]){
                                                              cube([60,43,2],center=true);
                                                            }
                                                          }
                                                        }
                                                        translate([-14.5,-13,-7]){
                                                          difference(){
                                                            translate([0,0,-8]){
                                                              rotate(a=-90,v=[0,1000,0]){
                                                                rotate([0,90,0]){cylinder($fn=100,h=16,r=3.5,center=true);}
                                                              }
                                                            }
                                                            rotate(a=90,v=[0,1000,0]){
                                                              translate([-0.6,0,0]){
                                                                translate([-0.4,0,0]){
                                                                  translate([-0.05,0,0]){
                                                                    translate([0.745,0,0]){
                                                                      rotate([0,90,0]){cylinder($fn=100,h=1.49,r1=2.1,r2=1.1,center=true);}
                                                                    }
                                                                  }
                                                                  translate([13.4,0,0]){
                                                                    translate([-6.7,0,0]){
                                                                      rotate([0,90,0]){cylinder($fn=100,h=13.4,r=1.1,center=true);}
                                                                    }
                                                                  }
                                                                }
                                                                translate([3,0,0]){
                                                                  translate([1,0,0]){
                                                                    rotate([0,90,0]){cylinder($fn=6,h=2,r=2.42487,center=true);}
                                                                  }
                                                                  translate([1,0,-5]){
                                                                    cube([2,4.2,10],center=true);
                                                                  }
                                                                  translate([0,0,-2]){
                                                                    difference(){
                                                                      translate([-5,0,-5]){
                                                                        cube([10,4.2,10],center=true);
                                                                      }
                                                                      rotate(a=30,v=[0,1000,0]){
                                                                        translate([-10,0,-10]){
                                                                          cube([20,8,20],center=true);
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                        difference(){
                                                          translate([9.55,0,-7]){
                                                            translate([0,0,-8]){
                                                              cube([5,7,16],center=true);
                                                            }
                                                          }
                                                          translate([11.5,0,0]){
                                                            translate([25,0,0]){
                                                              cube([50,50,50],center=true);
                                                            }
                                                          }
                                                        }
                                                      }
                                                      translate([-17.7,6.75,-12.8]){
                                                        translate([0,6.4,0]){
                                                          cube([20.5,12.8,9.6],center=true);
                                                        }
                                                      }
                                                    }
                                                    difference(){
                                                      translate([-2.7,-12.1,-20]){
                                                        difference(){
                                                          rotate(a=-30,v=[0,1000,0]){
                                                            translate([0,0,-3.5]){
                                                              cube([18,15,7],center=true);
                                                            }
                                                          }
                                                          translate([9.5,0,0]){
                                                            translate([5,0,0]){
                                                              cube([10,30,30],center=true);
                                                            }
                                                          }
                                                        }
                                                      }
                                                      translate([0,0,-22]){
                                                        translate([0,0,-10]){
                                                          cube([120,86,20],center=true);
                                                        }
                                                      }
                                                    }
                                                  }
                                                  translate([-2.7,-12.1,-20]){
                                                    rotate(a=-30,v=[0,1000,0]){
                                                      translate([5,0,0]){
                                                        translate([0,3.4,0]){
                                                          translate([-1,0,-2.6]){
                                                            rotate(a=-90,v=[0,1000,0]){
                                                              translate([1,0,0]){
                                                                rotate([0,90,0]){cylinder($fn=6,h=2,r=2.42487,center=true);}
                                                              }
                                                              translate([1,0,-2.5]){
                                                                cube([2,4.2,5],center=true);
                                                              }
                                                            }
                                                          }
                                                          translate([1,0,0]){
                                                            cube([5.2,2.2,8.8],center=true);
                                                          }
                                                        }
                                                        translate([0,-3.4,0]){
                                                          translate([-1,0,-2.6]){
                                                            rotate(a=-90,v=[0,1000,0]){
                                                              translate([1,0,0]){
                                                                rotate([0,90,0]){cylinder($fn=6,h=2,r=2.42487,center=true);}
                                                              }
                                                              translate([1,0,-2.5]){
                                                                cube([2,4.2,5],center=true);
                                                              }
                                                            }
                                                          }
                                                          translate([1,0,0]){
                                                            cube([5.2,2.2,8.8],center=true);
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                                translate([-36.65,-0.48,-21]){
                                                  translate([0,0,1.5]){
                                                    cube([15.7,24.25,3],center=true);
                                                  }
                                                  translate([0,0,1]){
                                                    cube([12.7,26.25,2],center=true);
                                                  }
                                                  translate([0,-12.625,0]){
                                                    difference(){
                                                      difference(){
                                                        translate([0,-1,3]){
                                                          cube([12,2,6],center=true);
                                                        }
                                                        translate([0,0,3]){
                                                          cube([1,10,1],center=true);
                                                        }
                                                      }
                                                      translate([0,0,6]){
                                                        cube([1,10,0.8],center=true);
                                                      }
                                                    }
                                                  }
                                                }
                                                translate([-45.5,-0.48,-19]){
                                                  translate([0,-8.625,0]){
                                                    translate([1.5,0,2.5]){
                                                      cube([3,2,5],center=true);
                                                    }
                                                  }
                                                  translate([0,8.625,0]){
                                                    translate([1.5,0,2.5]){
                                                      cube([3,2,5],center=true);
                                                    }
                                                  }
                                                }
                                                translate([-28.3,-6.98,-9]){
                                                  translate([-2,0,-10]){
                                                    cube([8,8,20],center=true);
                                                  }
                                                }
                                              }
                                              translate([-28.3,-6.98,-9]){
                                                translate([2.5,0,0]){
                                                  translate([1,0,0]){
                                                    cube([2,11,15],center=true);
                                                  }
                                                }
                                                rotate(a=90,v=[0,1000,0]){
                                                  rotate(a=150,v=[1000,0,0]){
                                                    translate([-3.25,0,0]){
                                                      rotate([0,90,0]){cylinder($fn=100,h=6.5,r=2.1,center=true);}
                                                    }
                                                    translate([13,0,0]){
                                                      translate([-6.875,0,0]){
                                                        rotate([0,90,0]){cylinder($fn=100,h=13.75,r=1.1,center=true);}
                                                      }
                                                    }
                                                    translate([10,0,0]){
                                                      translate([1,0,0]){
                                                        rotate([0,90,0]){cylinder($fn=6,h=2,r=2.33827,center=true);}
                                                      }
                                                      translate([1,0,-2.5]){
                                                        cube([2,4.05,5],center=true);
                                                      }
                                                      translate([0,0,-2]){
                                                        difference(){
                                                          translate([-2.5,0,-2.5]){
                                                            cube([5,4.05,5],center=true);
                                                          }
                                                          rotate(a=30,v=[0,1000,0]){
                                                            translate([-5,0,-5]){
                                                              cube([10,8,10],center=true);
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                            translate([-41.65,-0.48,-21]){
                                              rotate(a=30,v=[0,1000,0]){
                                                translate([0,8.625,0]){
                                                  translate([0,0,5]){
                                                    rotate(a=-90,v=[0,1000,0]){
                                                      rotate([0,90,0]){cylinder($fn=100,h=10,r=2,center=true);}
                                                    }
                                                  }
                                                }
                                                translate([0,-8.625,0]){
                                                  translate([0,0,5]){
                                                    rotate(a=-90,v=[0,1000,0]){
                                                      rotate([0,90,0]){cylinder($fn=100,h=10,r=2,center=true);}
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                          translate([-41.65,-0.48,-21]){
                                            rotate(a=30,v=[0,1000,0]){
                                              translate([0,8.625,0]){
                                                translate([0,0,0.5]){
                                                  cube([4,0.5,1],center=true);
                                                }
                                                translate([0,0,0.5]){
                                                  cube([0.5,4,1],center=true);
                                                }
                                              }
                                              translate([0,-8.625,0]){
                                                translate([0,0,0.5]){
                                                  cube([4,0.5,1],center=true);
                                                }
                                              }
                                            }
                                          }
                                        }
                                        translate([-36.65,0.52,-14.65]){
                                          rotate(a=90,v=[0,0,1000]){
                                            rotate([0,90,0]){cylinder($fn=100,h=27.25,r=7.4,center=true);}
                                          }
                                        }
                                      }
                                      translate([-28.3,-6.98,-15]){
                                        translate([0,0,10]){
                                          cube([8,9,20],center=true);
                                        }
                                      }
                                    }
                                    translate([-36.65,10.645,-21]){
                                      translate([0,2.5,15]){
                                        cube([15.7,5,30],center=true);
                                      }
                                    }
                                  }
                                  difference(){
                                    translate([-36.65,12.295,-20.8]){
                                      difference(){
                                        translate([0,0,4.5]){
                                          cube([10,1.3,9],center=true);
                                        }
                                        cube([8,10,0.4],center=true);
                                      }
                                      translate([-5,4.3,0]){
                                        translate([6.5,0,4.5]){
                                          cube([13,1.3,9],center=true);
                                        }
                                      }
                                      translate([-5,2.15,0]){
                                        difference(){
                                          difference(){
                                            translate([0,0,4.5]){
                                              rotate(a=-90,v=[0,1000,0]){
                                                rotate([0,90,0]){cylinder($fn=100,h=9,r=2.8,center=true);}
                                              }
                                            }
                                            rotate(a=-90,v=[0,1000,0]){
                                              rotate([0,90,0]){cylinder($fn=100,h=27,r=1.5,center=true);}
                                            }
                                          }
                                          translate([4.5,0,0]){
                                            cube([9,9,27],center=true);
                                          }
                                        }
                                      }
                                    }
                                    translate([-36.65,12.295,-14.65]){
                                      translate([0,0,2]){
                                        cube([1,2.6,1],center=true);
                                      }
                                      translate([0,0,-2]){
                                        cube([1,2.6,1],center=true);
                                      }
                                    }
                                  }
                                  difference(){
                                    difference(){
                                      translate([-12.7,6.75,-12.8]){
                                        translate([-15.25,0,0]){
                                          translate([0,0.2,0]){
                                            translate([-0.5,6.4,0]){
                                              cube([1,12.8,36],center=true);
                                            }
                                          }
                                          translate([0,-1.2,0]){
                                            translate([-0.5,-2.1,0]){
                                              cube([1,4.2,36],center=true);
                                            }
                                          }
                                          translate([0,-3.9,4.8]){
                                            translate([-0.5,8.5,9]){
                                              cube([1,17,18],center=true);
                                            }
                                          }
                                          translate([-1,-4.6,-4.8]){
                                            translate([3,0,4]){
                                              translate([-1.5,-1.5,-9]){
                                                cube([3,3,18],center=true);
                                              }
                                            }
                                          }
                                        }
                                      }
                                      translate([0,0,-7]){
                                        translate([0,0,5]){
                                          cube([100,100,10],center=true);
                                        }
                                      }
                                    }
                                    translate([-12.7,6.75,-12.8]){
                                      translate([-15.25,0,0]){
                                        translate([-1,-4.6,-4.8]){
                                          translate([3,0.7,4]){
                                            rotate(a=55,v=[0,1000,0]){
                                              translate([0,-10,7.5]){
                                                cube([20,20,20],center=true);
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                  translate([-12.7,6.75,-12.8]){
                                    translate([-15.25,0,0]){
                                      translate([-1,-4.6,-4.8]){
                                        translate([13.05,8.5,-9]){
                                          cube([26.1,17,18],center=true);
                                        }
                                      }
                                    }
                                  }
                                  translate([-12.7,6.75,-12.8]){
                                    translate([6.05,0,-4.9]){
                                      translate([0,0.2,0]){
                                        translate([1.9,4,1]){
                                          cube([3.8,8,2],center=true);
                                        }
                                      }
                                      translate([0,-1.2,0]){
                                        translate([1.9,-1,1]){
                                          cube([3.8,2,2],center=true);
                                        }
                                      }
                                    }
                                  }
                                  difference(){
                                    difference(){
                                      translate([-0.65,11.75,-7.2]){
                                        translate([0,0,-7]){
                                          rotate(a=-90,v=[0,1000,0]){
                                            rotate([0,90,0]){cylinder($fn=100,h=14,r=3.5,center=true);}
                                          }
                                        }
                                        translate([-3.5,0,-2.5]){
                                          cube([7,7,5],center=true);
                                        }
                                        translate([-4.5,0,-0.5]){
                                          cube([9,7,1],center=true);
                                        }
                                      }
                                      translate([-0.65,11.75,-7.2]){
                                        rotate(a=90,v=[0,1000,0]){
                                          translate([-2.5,0,0]){
                                            rotate([0,90,0]){cylinder($fn=100,h=5,r=2.1,center=true);}
                                          }
                                          translate([-0.05,0,0]){
                                            translate([0.745,0,0]){
                                              rotate([0,90,0]){cylinder($fn=100,h=1.49,r1=2.1,r2=1.1,center=true);}
                                            }
                                          }
                                          translate([11,0,0]){
                                            translate([-5.5,0,0]){
                                              rotate([0,90,0]){cylinder($fn=100,h=11,r=1.1,center=true);}
                                            }
                                          }
                                          translate([8,0,0]){
                                            rotate(a=-90,v=[1000,0,0]){
                                              translate([1,0,0]){
                                                rotate([0,90,0]){cylinder($fn=6,h=2,r=2.42487,center=true);}
                                              }
                                              translate([1,0,-5]){
                                                cube([2,4.2,10],center=true);
                                              }
                                              translate([0,0,-2]){
                                                difference(){
                                                  translate([-5,0,-5]){
                                                    cube([10,4.2,10],center=true);
                                                  }
                                                  rotate(a=30,v=[0,1000,0]){
                                                    translate([-10,0,-10]){
                                                      cube([20,8,20],center=true);
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                    translate([-0.65,11.75,-13.2]){
                                      translate([0,0,25]){
                                        cube([50,50,50],center=true);
                                      }
                                    }
                                  }
                                }
                                translate([-17.5,19.5,-21]){
                                  translate([0,-1,2]){
                                    cube([54,2,4],center=true);
                                  }
                                }
                              }
                              translate([-45.5,0,-21]){
                                translate([0.75,0,1.5]){
                                  cube([1.5,25.25,3],center=true);
                                }
                              }
                            }
                            translate([0,0,-21]){
                              translate([0,0,5]){
                                cube([13.8,7.5,10],center=true);
                              }
                            }
                          }
                          difference(){
                            translate([-44.95,17,-7]){
                              translate([0,2,-9]){
                                cube([4.60359,4,18],center=true);
                              }
                            }
                            translate([-47.5,19.5,-12]){
                              rotate(a=-32,v=[1000,0,0]){
                                translate([0,0,-10]){
                                  cube([20,20,20],center=true);
                                }
                              }
                            }
                          }
                          translate([-44.95,-17,-7]){
                            translate([0,-2,-9]){
                              cube([4.60359,4,18],center=true);
                            }
                          }
                        }
                        translate([-44.95,0,-9]){
                          rotate(a=90,v=[0,0,1000]){
                            rotate([0,90,0]){cylinder($fn=100,h=41,r=1.05179,center=true);}
                          }
                        }
                      }
                      difference(){
                        translate([-25.5,-19.5,-7.5]){
                          difference(){
                            translate([0,1.25,-9]){
                              cube([12,2.5,18],center=true);
                            }
                            translate([0,2.5,0]){
                              rotate(a=-30,v=[1000,0,0]){
                                cube([60,10,1.5],center=true);
                              }
                            }
                          }
                        }
                        translate([-44.95,-19.5,-9]){
                          difference(){
                            difference(){
                              rotate(a=90,v=[0,0,1000]){
                                rotate([0,90,0]){cylinder($fn=100,h=8,r=24.5,center=true);}
                              }
                              rotate(a=90,v=[0,0,1000]){
                                rotate([0,90,0]){cylinder($fn=100,h=9,r=18.5,center=true);}
                              }
                            }
                            translate([0,0,250]){
                              cube([100,500,500],center=true);
                            }
                          }
                        }
                      }
                    }
                    translate([11.55,0,-7]){
                      translate([-5,0,0]){
                        cube([10,11.4,2.8],center=true);
                      }
                    }
                  }
                  translate([9.55,0,-5]){
                    rotate(a=90,v=[0,1000,0]){
                      rotate(a=30,v=[1000,0,0]){
                        translate([-0.05,0,0]){
                          translate([0.745,0,0]){
                            rotate([0,90,0]){cylinder($fn=100,h=1.49,r1=2.1,r2=1.1,center=true);}
                          }
                        }
                        translate([13,0,0]){
                          translate([-6.5,0,0]){
                            rotate([0,90,0]){cylinder($fn=100,h=13,r=1.1,center=true);}
                          }
                        }
                        translate([6,0,0]){
                          translate([1,0,0]){
                            rotate([0,90,0]){cylinder($fn=6,h=2,r=2.42487,center=true);}
                          }
                          translate([1,0,-5]){
                            cube([2,4.2,10],center=true);
                          }
                          translate([0,0,-2]){
                            difference(){
                              translate([-5,0,-5]){
                                cube([10,4.2,10],center=true);
                              }
                              rotate(a=30,v=[0,1000,0]){
                                translate([-10,0,-10]){
                                  cube([20,8,20],center=true);
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
                translate([-47.5,0,-11.2]){
                  rotate(a=30,v=[0,1000,0]){
                    translate([0,0,5]){
                      cube([6,34,10],center=true);
                    }
                  }
                }
              }
              translate([-47.5,0,-7]){
                rotate(a=-60,v=[0,1000,0]){
                  cube([10,86,2],center=true);
                }
              }
            }
            translate([-16.7,-4.25,-21]){
              cube([18,12,2],center=true);
            }
          }
          translate([0,0,-7]){
            translate([0,0,-7.5]){
              cube([15.8,8,15],center=true);
            }
          }
        }
        translate([0,0,-7]){
          translate([0,0,-3.8]){
            cube([15.5,7.7,7.6],center=true);
          }
        }
      }
      translate([-17.5,0,-7]){
        translate([0,0,10]){
          cube([56,39,20],center=true);
        }
        translate([0,0,0.6]){
          translate([0,0,10]){
            cube([62,45,20],center=true);
          }
        }
        translate([0,0,-16]){
          translate([0,0,-10]){
            cube([62,45,20],center=true);
          }
        }
      }
    }
    translate([12.5,0,0]){
      translate([10,0,0]){
        cube([20,129,54],center=true);
      }
    }
  }
}
}
