/* -*- Mode: C -*- */
/* Automatically generated by Hob3l fontgen; DO NOT EDIT */
/* Copyright (C) 2018-2023 by Henrik Theiling, Licence: GPLv3, see LICENSE file */

#ifndef CP_FONT_NOZZL3_SANS_H_
#define CP_FONT_NOZZL3_SANS_H_

#include <hob3l/font_tam.h>

extern cp_font_t const cp_font_nozzl3_sans;
extern cp_font_t const cp_font_nozzl3_sans_oblique;
extern cp_font_t const cp_font_nozzl3_sans_medium;
extern cp_font_t const cp_font_nozzl3_sans_medium_oblique;
extern cp_font_t const cp_font_nozzl3_sans_bold;
extern cp_font_t const cp_font_nozzl3_sans_bold_oblique;
extern cp_font_t const cp_font_nozzl3_sans_black;
extern cp_font_t const cp_font_nozzl3_sans_black_oblique;
extern cp_font_t const cp_font_nozzl3_sans_light;
extern cp_font_t const cp_font_nozzl3_sans_light_oblique;

#endif /* CP_FONT_NOZZL3_SANS_H_ */
