union(){
  difference(){
    difference(){
      difference(){
        difference(){
          difference(){
            difference(){
              difference(){
                difference(){
                  difference(){
                    union(){
                      difference(){
                        union(){
                          difference(){
                            difference(){
                              difference(){
                                union(){
                                  difference(){
                                    difference(){
                                      difference(){
                                        union(){
                                          difference(){
                                            difference(){
                                              union(){
                                                difference(){
                                                  union(){
                                                    difference(){
                                                      union(){
                                                        translate(v=[12.5,0,-7]){
                                                          translate(v=[-1.65,0,0]){
                                                            cube(size=[0.7,35,1.2],center=true);
                                                          }
                                                          translate(v=[-4,0,0]){
                                                            translate(v=[0,19.85,0]){
                                                              translate(v=[-6.25,0,0]){
                                                                cube(size=[12.5,0.7,1.2],center=true);
                                                              }
                                                            }
                                                            translate(v=[0,-19.85,0]){
                                                              translate(v=[-6.25,0,0]){
                                                                cube(size=[12.5,0.7,1.2],center=true);
                                                              }
                                                            }
                                                          }
                                                        }
                                                        translate(v=[12.5,0,-7]){
                                                          translate(v=[-1,0,-8]){
                                                            cube(size=[2,43,16],center=true);
                                                          }
                                                          translate(v=[-60,0,0]){
                                                            translate(v=[1,0,-8]){
                                                              cube(size=[2,43,16],center=true);
                                                            }
                                                          }
                                                          translate(v=[0,21.5,0]){
                                                            translate(v=[-30,-1,-8]){
                                                              cube(size=[60,2,16],center=true);
                                                            }
                                                          }
                                                          translate(v=[0,-21.5,0]){
                                                            translate(v=[-30,1,-8]){
                                                              cube(size=[60,2,16],center=true);
                                                            }
                                                          }
                                                          translate(v=[0,0,-16]){
                                                            translate(v=[-30,0,1]){
                                                              cube(size=[60,43,2],center=true);
                                                            }
                                                          }
                                                        }
                                                        translate(v=[-14.5,-13,-7]){
                                                          difference(){
                                                            translate(v=[0,0,-8]){
                                                              rotate(a=-90,v=[0,1000,0]){
                                                                rotate(a=[0,90,0]){
                                                                  cylinder(h=16,r1=3.5,r2=3.5,center=true,$fa=12,$fs=2,$fn=100);
                                                                }
                                                              }
                                                            }
                                                            rotate(a=90,v=[0,1000,0]){
                                                              translate(v=[-0.6,0,0]){
                                                                translate(v=[-0.4,0,0]){
                                                                  translate(v=[-0.05,0,0]){
                                                                    translate(v=[0.745,0,0]){
                                                                      rotate(a=[0,90,0]){
                                                                        cylinder(h=1.49,r1=2.1,r2=1.1,center=true,$fa=12,$fs=2,$fn=100);
                                                                      }
                                                                    }
                                                                  }
                                                                  translate(v=[13.4,0,0]){
                                                                    translate(v=[-6.7,0,0]){
                                                                      rotate(a=[0,90,0]){
                                                                        cylinder(h=13.4,r1=1.1,r2=1.1,center=true,$fa=12,$fs=2,$fn=100);
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                                translate(v=[3,0,0]){
                                                                  translate(v=[1,0,0]){
                                                                    rotate(a=[0,90,0]){
                                                                      cylinder(h=2,r1=2.42487,r2=2.42487,center=true,$fa=12,$fs=2,$fn=6);
                                                                    }
                                                                  }
                                                                  translate(v=[1,0,-5]){
                                                                    cube(size=[2,4.2,10],center=true);
                                                                  }
                                                                  translate(v=[0,0,-2]){
                                                                    difference(){
                                                                      translate(v=[-5,0,-5]){
                                                                        cube(size=[10,4.2,10],center=true);
                                                                      }
                                                                      rotate(a=30,v=[0,1000,0]){
                                                                        translate(v=[-10,0,-10]){
                                                                          cube(size=[20,8,20],center=true);
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                        difference(){
                                                          translate(v=[9.55,0,-7]){
                                                            translate(v=[0,0,-8]){
                                                              cube(size=[5,7,16],center=true);
                                                            }
                                                          }
                                                          translate(v=[11.5,0,0]){
                                                            translate(v=[25,0,0]){
                                                              cube(size=[50,50,50],center=true);
                                                            }
                                                          }
                                                        }
                                                      }
                                                      translate(v=[-17.7,6.75,-12.8]){
                                                        translate(v=[0,6.4,0]){
                                                          cube(size=[20.5,12.8,9.6],center=true);
                                                        }
                                                      }
                                                    }
                                                    difference(){
                                                      translate(v=[-2.7,-12.1,-20]){
                                                        difference(){
                                                          rotate(a=-30,v=[0,1000,0]){
                                                            translate(v=[0,0,-3.5]){
                                                              cube(size=[18,15,7],center=true);
                                                            }
                                                          }
                                                          translate(v=[9.5,0,0]){
                                                            translate(v=[5,0,0]){
                                                              cube(size=[10,30,30],center=true);
                                                            }
                                                          }
                                                        }
                                                      }
                                                      translate(v=[0,0,-22]){
                                                        translate(v=[0,0,-10]){
                                                          cube(size=[120,86,20],center=true);
                                                        }
                                                      }
                                                    }
                                                  }
                                                  translate(v=[-2.7,-12.1,-20]){
                                                    rotate(a=-30,v=[0,1000,0]){
                                                      translate(v=[5,0,0]){
                                                        translate(v=[0,3.4,0]){
                                                          translate(v=[-1,0,-2.6]){
                                                            rotate(a=-90,v=[0,1000,0]){
                                                              translate(v=[1,0,0]){
                                                                rotate(a=[0,90,0]){
                                                                  cylinder(h=2,r1=2.42487,r2=2.42487,center=true,$fa=12,$fs=2,$fn=6);
                                                                }
                                                              }
                                                              translate(v=[1,0,-2.5]){
                                                                cube(size=[2,4.2,5],center=true);
                                                              }
                                                            }
                                                          }
                                                          translate(v=[1,0,0]){
                                                            cube(size=[5.2,2.2,8.8],center=true);
                                                          }
                                                        }
                                                        translate(v=[0,-3.4,0]){
                                                          translate(v=[-1,0,-2.6]){
                                                            rotate(a=-90,v=[0,1000,0]){
                                                              translate(v=[1,0,0]){
                                                                rotate(a=[0,90,0]){
                                                                  cylinder(h=2,r1=2.42487,r2=2.42487,center=true,$fa=12,$fs=2,$fn=6);
                                                                }
                                                              }
                                                              translate(v=[1,0,-2.5]){
                                                                cube(size=[2,4.2,5],center=true);
                                                              }
                                                            }
                                                          }
                                                          translate(v=[1,0,0]){
                                                            cube(size=[5.2,2.2,8.8],center=true);
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                                translate(v=[-36.65,-0.48,-21]){
                                                  translate(v=[0,0,1.5]){
                                                    cube(size=[15.7,24.25,3],center=true);
                                                  }
                                                  translate(v=[0,0,1]){
                                                    cube(size=[12.7,26.25,2],center=true);
                                                  }
                                                  translate(v=[0,-12.625,0]){
                                                    difference(){
                                                      difference(){
                                                        translate(v=[0,-1,3]){
                                                          cube(size=[12,2,6],center=true);
                                                        }
                                                        translate(v=[0,0,3]){
                                                          cube(size=[1,10,1],center=true);
                                                        }
                                                      }
                                                      translate(v=[0,0,6]){
                                                        cube(size=[1,10,0.8],center=true);
                                                      }
                                                    }
                                                  }
                                                }
                                                translate(v=[-45.5,-0.48,-19]){
                                                  translate(v=[0,-8.625,0]){
                                                    translate(v=[1.5,0,2.5]){
                                                      cube(size=[3,2,5],center=true);
                                                    }
                                                  }
                                                  translate(v=[0,8.625,0]){
                                                    translate(v=[1.5,0,2.5]){
                                                      cube(size=[3,2,5],center=true);
                                                    }
                                                  }
                                                }
                                                translate(v=[-28.3,-6.98,-9]){
                                                  translate(v=[-2,0,-10]){
                                                    cube(size=[8,8,20],center=true);
                                                  }
                                                }
                                              }
                                              translate(v=[-28.3,-6.98,-9]){
                                                translate(v=[2.5,0,0]){
                                                  translate(v=[1,0,0]){
                                                    cube(size=[2,11,15],center=true);
                                                  }
                                                }
                                                rotate(a=90,v=[0,1000,0]){
                                                  rotate(a=150,v=[1000,0,0]){
                                                    translate(v=[-3.25,0,0]){
                                                      rotate(a=[0,90,0]){
                                                        cylinder(h=6.5,r1=2.1,r2=2.1,center=true,$fa=12,$fs=2,$fn=100);
                                                      }
                                                    }
                                                    translate(v=[13,0,0]){
                                                      translate(v=[-6.875,0,0]){
                                                        rotate(a=[0,90,0]){
                                                          cylinder(h=13.75,r1=1.1,r2=1.1,center=true,$fa=12,$fs=2,$fn=100);
                                                        }
                                                      }
                                                    }
                                                    translate(v=[10,0,0]){
                                                      translate(v=[1,0,0]){
                                                        rotate(a=[0,90,0]){
                                                          cylinder(h=2,r1=2.33827,r2=2.33827,center=true,$fa=12,$fs=2,$fn=6);
                                                        }
                                                      }
                                                      translate(v=[1,0,-2.5]){
                                                        cube(size=[2,4.05,5],center=true);
                                                      }
                                                      translate(v=[0,0,-2]){
                                                        difference(){
                                                          translate(v=[-2.5,0,-2.5]){
                                                            cube(size=[5,4.05,5],center=true);
                                                          }
                                                          rotate(a=30,v=[0,1000,0]){
                                                            translate(v=[-5,0,-5]){
                                                              cube(size=[10,8,10],center=true);
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                            translate(v=[-41.65,-0.48,-21]){
                                              rotate(a=30,v=[0,1000,0]){
                                                translate(v=[0,8.625,0]){
                                                  translate(v=[0,0,5]){
                                                    rotate(a=-90,v=[0,1000,0]){
                                                      rotate(a=[0,90,0]){
                                                        cylinder(h=10,r1=2,r2=2,center=true,$fa=12,$fs=2,$fn=100);
                                                      }
                                                    }
                                                  }
                                                }
                                                translate(v=[0,-8.625,0]){
                                                  translate(v=[0,0,5]){
                                                    rotate(a=-90,v=[0,1000,0]){
                                                      rotate(a=[0,90,0]){
                                                        cylinder(h=10,r1=2,r2=2,center=true,$fa=12,$fs=2,$fn=100);
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                          translate(v=[-41.65,-0.48,-21]){
                                            rotate(a=30,v=[0,1000,0]){
                                              translate(v=[0,8.625,0]){
                                                translate(v=[0,0,0.5]){
                                                  cube(size=[4,0.5,1],center=true);
                                                }
                                                translate(v=[0,0,0.5]){
                                                  cube(size=[0.5,4,1],center=true);
                                                }
                                              }
                                              translate(v=[0,-8.625,0]){
                                                translate(v=[0,0,0.5]){
                                                  cube(size=[4,0.5,1],center=true);
                                                }
                                              }
                                            }
                                          }
                                        }
                                        translate(v=[-36.65,0.52,-14.65]){
                                          rotate(a=90,v=[0,0,1000]){
                                            rotate(a=[0,90,0]){
                                              cylinder(h=27.25,r1=7.4,r2=7.4,center=true,$fa=12,$fs=2,$fn=100);
                                            }
                                          }
                                        }
                                      }
                                      translate(v=[-28.3,-6.98,-15]){
                                        translate(v=[0,0,10]){
                                          cube(size=[8,9,20],center=true);
                                        }
                                      }
                                    }
                                    translate(v=[-36.65,10.645,-21]){
                                      translate(v=[0,2.5,15]){
                                        cube(size=[15.7,5,30],center=true);
                                      }
                                    }
                                  }
                                  difference(){
                                    translate(v=[-36.65,12.295,-20.8]){
                                      difference(){
                                        translate(v=[0,0,4.5]){
                                          cube(size=[10,1.3,9],center=true);
                                        }
                                        cube(size=[8,10,0.4],center=true);
                                      }
                                      translate(v=[-5,4.3,0]){
                                        translate(v=[6.5,0,4.5]){
                                          cube(size=[13,1.3,9],center=true);
                                        }
                                      }
                                      translate(v=[-5,2.15,0]){
                                        difference(){
                                          difference(){
                                            translate(v=[0,0,4.5]){
                                              rotate(a=-90,v=[0,1000,0]){
                                                rotate(a=[0,90,0]){
                                                  cylinder(h=9,r1=2.8,r2=2.8,center=true,$fa=12,$fs=2,$fn=100);
                                                }
                                              }
                                            }
                                            rotate(a=-90,v=[0,1000,0]){
                                              rotate(a=[0,90,0]){
                                                cylinder(h=27,r1=1.5,r2=1.5,center=true,$fa=12,$fs=2,$fn=100);
                                              }
                                            }
                                          }
                                          translate(v=[4.5,0,0]){
                                            cube(size=[9,9,27],center=true);
                                          }
                                        }
                                      }
                                    }
                                    translate(v=[-36.65,12.295,-14.65]){
                                      translate(v=[0,0,2]){
                                        cube(size=[1,2.6,1],center=true);
                                      }
                                      translate(v=[0,0,-2]){
                                        cube(size=[1,2.6,1],center=true);
                                      }
                                    }
                                  }
                                  difference(){
                                    difference(){
                                      translate(v=[-12.7,6.75,-12.8]){
                                        translate(v=[-15.25,0,0]){
                                          translate(v=[0,0.2,0]){
                                            translate(v=[-0.5,6.4,0]){
                                              cube(size=[1,12.8,36],center=true);
                                            }
                                          }
                                          translate(v=[0,-1.2,0]){
                                            translate(v=[-0.5,-2.1,0]){
                                              cube(size=[1,4.2,36],center=true);
                                            }
                                          }
                                          translate(v=[0,-3.9,4.8]){
                                            translate(v=[-0.5,8.5,9]){
                                              cube(size=[1,17,18],center=true);
                                            }
                                          }
                                          translate(v=[-1,-4.6,-4.8]){
                                            translate(v=[3,0,4]){
                                              translate(v=[-1.5,-1.5,-9]){
                                                cube(size=[3,3,18],center=true);
                                              }
                                            }
                                          }
                                        }
                                      }
                                      translate(v=[0,0,-7]){
                                        translate(v=[0,0,5]){
                                          cube(size=[100,100,10],center=true);
                                        }
                                      }
                                    }
                                    translate(v=[-12.7,6.75,-12.8]){
                                      translate(v=[-15.25,0,0]){
                                        translate(v=[-1,-4.6,-4.8]){
                                          translate(v=[3,0.7,4]){
                                            rotate(a=55,v=[0,1000,0]){
                                              translate(v=[0,-10,7.5]){
                                                cube(size=[20,20,20],center=true);
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                  translate(v=[-12.7,6.75,-12.8]){
                                    translate(v=[-15.25,0,0]){
                                      translate(v=[-1,-4.6,-4.8]){
                                        translate(v=[13.05,8.5,-9]){
                                          cube(size=[26.1,17,18],center=true);
                                        }
                                      }
                                    }
                                  }
                                  translate(v=[-12.7,6.75,-12.8]){
                                    translate(v=[6.05,0,-4.9]){
                                      translate(v=[0,0.2,0]){
                                        translate(v=[1.9,4,1]){
                                          cube(size=[3.8,8,2],center=true);
                                        }
                                      }
                                      translate(v=[0,-1.2,0]){
                                        translate(v=[1.9,-1,1]){
                                          cube(size=[3.8,2,2],center=true);
                                        }
                                      }
                                    }
                                  }
                                  difference(){
                                    difference(){
                                      translate(v=[-0.65,11.75,-7.2]){
                                        translate(v=[0,0,-7]){
                                          rotate(a=-90,v=[0,1000,0]){
                                            rotate(a=[0,90,0]){
                                              cylinder(h=14,r1=3.5,r2=3.5,center=true,$fa=12,$fs=2,$fn=100);
                                            }
                                          }
                                        }
                                        translate(v=[-3.5,0,-2.5]){
                                          cube(size=[7,7,5],center=true);
                                        }
                                        translate(v=[-4.5,0,-0.5]){
                                          cube(size=[9,7,1],center=true);
                                        }
                                      }
                                      translate(v=[-0.65,11.75,-7.2]){
                                        rotate(a=90,v=[0,1000,0]){
                                          translate(v=[-2.5,0,0]){
                                            rotate(a=[0,90,0]){
                                              cylinder(h=5,r1=2.1,r2=2.1,center=true,$fa=12,$fs=2,$fn=100);
                                            }
                                          }
                                          translate(v=[-0.05,0,0]){
                                            translate(v=[0.745,0,0]){
                                              rotate(a=[0,90,0]){
                                                cylinder(h=1.49,r1=2.1,r2=1.1,center=true,$fa=12,$fs=2,$fn=100);
                                              }
                                            }
                                          }
                                          translate(v=[11,0,0]){
                                            translate(v=[-5.5,0,0]){
                                              rotate(a=[0,90,0]){
                                                cylinder(h=11,r1=1.1,r2=1.1,center=true,$fa=12,$fs=2,$fn=100);
                                              }
                                            }
                                          }
                                          translate(v=[8,0,0]){
                                            rotate(a=-90,v=[1000,0,0]){
                                              translate(v=[1,0,0]){
                                                rotate(a=[0,90,0]){
                                                  cylinder(h=2,r1=2.42487,r2=2.42487,center=true,$fa=12,$fs=2,$fn=6);
                                                }
                                              }
                                              translate(v=[1,0,-5]){
                                                cube(size=[2,4.2,10],center=true);
                                              }
                                              translate(v=[0,0,-2]){
                                                difference(){
                                                  translate(v=[-5,0,-5]){
                                                    cube(size=[10,4.2,10],center=true);
                                                  }
                                                  rotate(a=30,v=[0,1000,0]){
                                                    translate(v=[-10,0,-10]){
                                                      cube(size=[20,8,20],center=true);
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                    translate(v=[-0.65,11.75,-13.2]){
                                      translate(v=[0,0,25]){
                                        cube(size=[50,50,50],center=true);
                                      }
                                    }
                                  }
                                }
                                translate(v=[-17.5,19.5,-21]){
                                  translate(v=[0,-1,2]){
                                    cube(size=[54,2,4],center=true);
                                  }
                                }
                              }
                              translate(v=[-45.5,0,-21]){
                                translate(v=[0.75,0,1.5]){
                                  cube(size=[1.5,25.25,3],center=true);
                                }
                              }
                            }
                            translate(v=[0,0,-21]){
                              translate(v=[0,0,5]){
                                cube(size=[13.8,7.5,10],center=true);
                              }
                            }
                          }
                          difference(){
                            translate(v=[-44.95,17,-7]){
                              translate(v=[0,2,-9]){
                                cube(size=[4.60359,4,18],center=true);
                              }
                            }
                            translate(v=[-47.5,19.5,-12]){
                              rotate(a=-32,v=[1000,0,0]){
                                translate(v=[0,0,-10]){
                                  cube(size=[20,20,20],center=true);
                                }
                              }
                            }
                          }
                          translate(v=[-44.95,-17,-7]){
                            translate(v=[0,-2,-9]){
                              cube(size=[4.60359,4,18],center=true);
                            }
                          }
                        }
                        translate(v=[-44.95,0,-9]){
                          rotate(a=90,v=[0,0,1000]){
                            rotate(a=[0,90,0]){
                              cylinder(h=41,r1=1.05179,r2=1.05179,center=true,$fa=12,$fs=2,$fn=100);
                            }
                          }
                        }
                      }
                      difference(){
                        translate(v=[-25.5,-19.5,-7.5]){
                          difference(){
                            translate(v=[0,1.25,-9]){
                              cube(size=[12,2.5,18],center=true);
                            }
                            translate(v=[0,2.5,0]){
                              rotate(a=-30,v=[1000,0,0]){
                                cube(size=[60,10,1.5],center=true);
                              }
                            }
                          }
                        }
                        translate(v=[-44.95,-19.5,-9]){
                          difference(){
                            difference(){
                              rotate(a=90,v=[0,0,1000]){
                                rotate(a=[0,90,0]){
                                  cylinder(h=8,r1=24.5,r2=24.5,center=true,$fa=12,$fs=2,$fn=100);
                                }
                              }
                              rotate(a=90,v=[0,0,1000]){
                                rotate(a=[0,90,0]){
                                  cylinder(h=9,r1=18.5,r2=18.5,center=true,$fa=12,$fs=2,$fn=100);
                                }
                              }
                            }
                            translate(v=[0,0,250]){
                              cube(size=[100,500,500],center=true);
                            }
                          }
                        }
                      }
                    }
                    translate(v=[11.55,0,-7]){
                      translate(v=[-5,0,0]){
                        cube(size=[10,11.4,2.8],center=true);
                      }
                    }
                  }
                  translate(v=[9.55,0,-5]){
                    rotate(a=90,v=[0,1000,0]){
                      rotate(a=30,v=[1000,0,0]){
                        translate(v=[-0.05,0,0]){
                          translate(v=[0.745,0,0]){
                            rotate(a=[0,90,0]){
                              cylinder(h=1.49,r1=2.1,r2=1.1,center=true,$fa=12,$fs=2,$fn=100);
                            }
                          }
                        }
                        translate(v=[13,0,0]){
                          translate(v=[-6.5,0,0]){
                            rotate(a=[0,90,0]){
                              cylinder(h=13,r1=1.1,r2=1.1,center=true,$fa=12,$fs=2,$fn=100);
                            }
                          }
                        }
                        translate(v=[6,0,0]){
                          translate(v=[1,0,0]){
                            rotate(a=[0,90,0]){
                              cylinder(h=2,r1=2.42487,r2=2.42487,center=true,$fa=12,$fs=2,$fn=6);
                            }
                          }
                          translate(v=[1,0,-5]){
                            cube(size=[2,4.2,10],center=true);
                          }
                          translate(v=[0,0,-2]){
                            difference(){
                              translate(v=[-5,0,-5]){
                                cube(size=[10,4.2,10],center=true);
                              }
                              rotate(a=30,v=[0,1000,0]){
                                translate(v=[-10,0,-10]){
                                  cube(size=[20,8,20],center=true);
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
                translate(v=[-47.5,0,-11.2]){
                  rotate(a=30,v=[0,1000,0]){
                    translate(v=[0,0,5]){
                      cube(size=[6,34,10],center=true);
                    }
                  }
                }
              }
              translate(v=[-47.5,0,-7]){
                rotate(a=-60,v=[0,1000,0]){
                  cube(size=[10,86,2],center=true);
                }
              }
            }
            translate(v=[-16.7,-4.25,-21]){
              cube(size=[18,12,2],center=true);
            }
          }
          translate(v=[0,0,-7]){
            translate(v=[0,0,-7.5]){
              cube(size=[15.8,8,15],center=true);
            }
          }
        }
        translate(v=[0,0,-7]){
          translate(v=[0,0,-3.8]){
            cube(size=[15.5,7.7,7.6],center=true);
          }
        }
      }
      translate(v=[-17.5,0,-7]){
        translate(v=[0,0,10]){
          cube(size=[56,39,20],center=true);
        }
        translate(v=[0,0,0.6]){
          translate(v=[0,0,10]){
            cube(size=[62,45,20],center=true);
          }
        }
        translate(v=[0,0,-16]){
          translate(v=[0,0,-10]){
            cube(size=[62,45,20],center=true);
          }
        }
      }
    }
    translate(v=[12.5,0,0]){
      translate(v=[10,0,0]){
        cube(size=[20,129,54],center=true);
      }
    }
  }
}
